#!/usr/bin/env ruby
require 'pty'
log_path = "log/rspec.log"
begin
  PTY.spawn( "rake parallel:spec > log/rspec.log" ) do |stdin, stdout, pid|
  begin
    stdin.each { |line| print line }
  rescue Errno::EIO
  end
end
rescue PTY::ChildExited
  puts "Child process exit!"
end

# find out if there were any errors  
log = open(log_path).read
examples = log.match(/(\d+) examples/)[0].to_i rescue 0
errors = log.match(/(\d+) errors/)[0].to_i rescue 0
if errors == 0 then
  errors = log.match(/(\d+) failure/)[0].to_i rescue 0
end
pending = log.match(/(\d+) pending/)[0].to_i rescue 0

if errors.zero?
  puts "0 failed! #{examples} run, #{pending} pending"
  # log Output when tests ran successfully:
  # puts "View spec results at #{File.expand_path(log_path)}"
  sleep 1
  exit 0
else
  puts "\SPECS FAILED!!"
  puts "View your rspec results at #{File.expand_path(log_path)}"
  puts
  puts "#{errors} failed! #{examples} run, #{pending} pending"
  # Open log Ooutput when tests failed
  # `open #{log_path}`
  exit 1
end
